// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtpEWwTL_RT0mpY38WNFWs_gljhmYKm2s',
    appId: '1:54739192037:web:b3199bc82007ea5ea8ec0c',
    messagingSenderId: '54739192037',
    projectId: 'tasqr-67885',
    authDomain: 'tasqr-67885.firebaseapp.com',
    storageBucket: 'tasqr-67885.appspot.com',
    measurementId: 'G-0P16B7W7Z5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNqZaTeH4kqDzOhExtWrWk7VaBtpQFMPk',
    appId: '1:54739192037:android:a1faff650b23ad61a8ec0c',
    messagingSenderId: '54739192037',
    projectId: 'tasqr-67885',
    storageBucket: 'tasqr-67885.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFgTY9wlAgNs8MrZf1avdqge8H0TwBmLo',
    appId: '1:54739192037:ios:fc1be1a26fbaf2e7a8ec0c',
    messagingSenderId: '54739192037',
    projectId: 'tasqr-67885',
    storageBucket: 'tasqr-67885.appspot.com',
    iosClientId: '54739192037-l58cac2ku0sv0nkb22vbipk2d0lkdemp.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasqrProject',
  );
}
